import {
  ApplicationHandleResult,
  GroupAtType,
  GroupMessageReaderFilter,
  LoginStatus,
  MessageReceiveOptType,
  MessageStatus,
  Relationship,
  ViewType,
} from '../../src/types/enum';
import { CbEvents, SdkEvent } from '../../src/constant';
import type {
  AccessFriendApplicationParams,
  AccessGroupApplicationParams,
  AccessMessageParams,
  AccessToGroupParams,
  AdvancedMsgParams,
  AdvancedQuoteMsgParams,
  AtMsgParams,
  CustomMsgParams,
  CustomSignalParams,
  FaceMessageParams,
  FetchSurroundingParams,
  FileMsgParamsByFullPath,
  FileMsgParamsByURL,
  FindMessageParams,
  GetAdvancedHistoryMsgParams,
  GetFriendApplicationListAsApplicationParams,
  GetFriendApplicationUnhandledCountParams,
  GetGroupApplicationListParams,
  GetGroupMemberByTimeParams,
  GetGroupMemberParams,
  GetGroupMessageReaderParams,
  GetHistoryMsgParams,
  GetInputstatesParams,
  GetOneConversationParams,
  GetSelfUnhandledApplyCountParams,
  ImageMsgParamsByURL,
  InitAndLoginConfig,
  InsertGroupMsgParams,
  InsertSingleMsgParams,
  LocationMsgParams,
  MergerMsgParams,
  OffsetParams,
  PartialUserItem,
  PinFriendParams,
  QuoteMsgParams,
  RemarkFriendParams,
  RtcActionParams,
  SearchFriendParams,
  SearchGroupMemberParams,
  SearchGroupParams,
  SearchLocalParams,
  SendGroupReadReceiptParams,
  SendMsgParams,
  SetBurnDurationParams,
  SetConversationExParams,
  SetConversationMsgDestructParams,
  SetConversationMsgDestructTimeParams,
  SetConversationPinParams,
  SetConversationPrivateStateParams,
  SetConversationRecvOptParams,
  SetFriendExParams,
  SetGroupMemberNickParams,
  SetGroupRoleParams,
  SetGroupVerificationParams,
  SetMemberPermissionParams,
  SignalingInviteParams,
  SoundMsgParamsByFullPath,
  SoundMsgParamsByURL,
  SplitConversationParams,
  TransferGroupParams,
  TypingUpdateParams,
  UpdateMemberInfoParams,
  VideoMsgParamsByFullPath,
  VideoMsgParamsByURL,
} from '../../src/types/params';
import type {
  AdvancedGetMessageResult,
  AtUsersInfoItem,
  CallingRoomData,
  FriendshipInfo,
  GroupHasReadInfo,
  GroupMessageReadInfo,
  GroupMessageReceiptInfo,
  IMConfig,
  ParticipantInfo,
  PicBaseInfo,
  ReceiptInfo,
  RtcInvite,
  RtcInviteResults,
  SearchedFriendsInfo,
  UploadProgress,
  WSEvent,
  WsResponse,
} from '../../src/types/entity';
import type {
  DataOfEvent,
  EventDataMap,
  SdkEventDataMap,
} from '../../src/types/eventData';

type AssertNever<T extends never> = T;
type MissingSdkEventData = AssertNever<
  Exclude<SdkEvent, keyof SdkEventDataMap>
>;

type Patch10PublicTypes = [
  AccessFriendApplicationParams,
  AccessGroupApplicationParams,
  AccessMessageParams,
  AccessToGroupParams,
  AdvancedGetMessageResult,
  AdvancedMsgParams,
  AdvancedQuoteMsgParams,
  AtMsgParams,
  AtUsersInfoItem,
  CallingRoomData,
  CustomMsgParams,
  CustomSignalParams,
  DataOfEvent<CbEvents.OnConnecting>,
  EventDataMap,
  FaceMessageParams,
  FetchSurroundingParams,
  FileMsgParamsByFullPath,
  FileMsgParamsByURL,
  FindMessageParams,
  FriendshipInfo,
  GetAdvancedHistoryMsgParams,
  GetFriendApplicationListAsApplicationParams,
  GetFriendApplicationUnhandledCountParams,
  GetGroupApplicationListParams,
  GetGroupMemberByTimeParams,
  GetGroupMemberParams,
  GetGroupMessageReaderParams,
  GetHistoryMsgParams,
  GetInputstatesParams,
  GetOneConversationParams,
  GetSelfUnhandledApplyCountParams,
  GroupHasReadInfo,
  GroupMessageReadInfo,
  GroupMessageReceiptInfo,
  IMConfig,
  ImageMsgParamsByURL,
  InitAndLoginConfig,
  InsertGroupMsgParams,
  InsertSingleMsgParams,
  LocationMsgParams,
  MergerMsgParams,
  OffsetParams,
  ParticipantInfo,
  PartialUserItem,
  PicBaseInfo,
  PinFriendParams,
  QuoteMsgParams,
  ReceiptInfo,
  RemarkFriendParams,
  RtcActionParams,
  RtcInvite,
  RtcInviteResults,
  SearchFriendParams,
  SearchGroupMemberParams,
  SearchGroupParams,
  SearchLocalParams,
  SearchedFriendsInfo,
  SendGroupReadReceiptParams,
  SendMsgParams,
  SetBurnDurationParams,
  SetConversationExParams,
  SetConversationMsgDestructParams,
  SetConversationMsgDestructTimeParams,
  SetConversationPinParams,
  SetConversationPrivateStateParams,
  SetConversationRecvOptParams,
  SetFriendExParams,
  SetGroupMemberNickParams,
  SetGroupRoleParams,
  SetGroupVerificationParams,
  SetMemberPermissionParams,
  SignalingInviteParams,
  SoundMsgParamsByFullPath,
  SoundMsgParamsByURL,
  SplitConversationParams,
  TransferGroupParams,
  TypingUpdateParams,
  UpdateMemberInfoParams,
  UploadProgress,
  VideoMsgParamsByFullPath,
  VideoMsgParamsByURL,
  WSEvent,
  WsResponse
];

void (undefined as unknown as Patch10PublicTypes);
void (undefined as unknown as MissingSdkEventData);
const patch10SyncFailure: DataOfEvent<CbEvents.OnSyncServerFailed> = undefined;
const patch10SyncFinish: DataOfEvent<CbEvents.OnSyncServerFinish> = undefined;
const patch10InvalidToken: DataOfEvent<CbEvents.OnUserTokenInvalid> = undefined;
void [patch10SyncFailure, patch10SyncFinish, patch10InvalidToken];
void [
  CbEvents.OnConnecting,
  MessageReceiveOptType.Normal,
  GroupAtType.AtMe,
  ViewType.History,
  MessageStatus.Succeed,
  ApplicationHandleResult.Agree,
  ApplicationHandleResult.Reject,
  Relationship.isBlack,
  Relationship.isFriend,
  LoginStatus.Logout,
  LoginStatus.Logging,
  LoginStatus.Logged,
  GroupMessageReaderFilter.UnRead,
];
