export const DatabaseErrorCode = {
  InitializationFailed: 10001,
  RecordNotFound: 10002,
  OperationTimedOut: 10003,
  /** @deprecated Use `InitializationFailed` instead. */
  ErrorInit: 10001,
  /** @deprecated Use `RecordNotFound` instead. */
  ErrorNoRecord: 10002,
  /** @deprecated Use `OperationTimedOut` instead. */
  ErrorDBTimeout: 10003,
};

export enum SdkEvent {
  Login = 'Login',
  OnConnectFailed = 'OnConnectFailed',
  OnConnectSuccess = 'OnConnectSuccess',
  OnConnecting = 'OnConnecting',
  OnKickedOffline = 'OnKickedOffline',
  OnSelfInfoUpdated = 'OnSelfInfoUpdated',
  OnUserTokenExpired = 'OnUserTokenExpired',
  OnUserTokenInvalid = 'OnUserTokenInvalid',
  OnProgress = 'OnProgress',
  OnRecvNewMessage = 'OnRecvNewMessage',
  OnRecvNewMessages = 'OnRecvNewMessages',
  OnRecvOnlineOnlyMessage = 'OnRecvOnlineOnlyMessage',
  OnRecvOfflineNewMessage = 'OnRecvOfflineNewMessage',
  OnRecvOfflineNewMessages = 'OnRecvOfflineNewMessages',
  /** @deprecated Use `OnRecvOnlineOnlyMessage` instead. */
  OnRecvOnlineOnlyMessages = 'OnRecvOnlineOnlyMessages',
  OnRecvMessageRevoked = 'OnRecvMessageRevoked',
  OnNewRecvMessageRevoked = 'OnNewRecvMessageRevoked',
  OnRecvMessageModified = 'OnRecvMessageModified',
  OnRecvMessageExtensionsChanged = 'OnRecvMessageExtensionsChanged',
  OnRecvMessageExtensionsDeleted = 'OnRecvMessageExtensionsDeleted',
  OnRecvMessageExtensionsAdded = 'OnRecvMessageExtensionsAdded',
  OnMsgDeleted = 'OnMsgDeleted',
  OnRecvC2CReadReceipt = 'OnRecvC2CReadReceipt',
  OnRecvGroupReadReceipt = 'OnRecvGroupReadReceipt',
  OnConversationChanged = 'OnConversationChanged',
  OnNewConversation = 'OnNewConversation',
  OnConversationUserInputStatusChanged = 'OnConversationUserInputStatusChanged',
  OnSyncServerFailed = 'OnSyncServerFailed',
  OnSyncServerFinish = 'OnSyncServerFinish',
  OnSyncServerProgress = 'OnSyncServerProgress',
  OnSyncServerStart = 'OnSyncServerStart',
  OnTotalUnreadMessageCountChanged = 'OnTotalUnreadMessageCountChanged',
  OnBlackAdded = 'OnBlackAdded',
  OnBlackDeleted = 'OnBlackDeleted',
  OnFriendApplicationAccepted = 'OnFriendApplicationAccepted',
  OnFriendApplicationAdded = 'OnFriendApplicationAdded',
  OnFriendApplicationDeleted = 'OnFriendApplicationDeleted',
  OnFriendApplicationRejected = 'OnFriendApplicationRejected',
  OnFriendInfoChanged = 'OnFriendInfoChanged',
  OnFriendAdded = 'OnFriendAdded',
  OnFriendDeleted = 'OnFriendDeleted',
  OnJoinedGroupAdded = 'OnJoinedGroupAdded',
  OnJoinedGroupDeleted = 'OnJoinedGroupDeleted',
  OnGroupDismissed = 'OnGroupDismissed',
  OnGroupMemberAdded = 'OnGroupMemberAdded',
  OnGroupMemberDeleted = 'OnGroupMemberDeleted',
  OnGroupApplicationAdded = 'OnGroupApplicationAdded',
  OnGroupApplicationDeleted = 'OnGroupApplicationDeleted',
  OnGroupInfoChanged = 'OnGroupInfoChanged',
  OnGroupMemberInfoChanged = 'OnGroupMemberInfoChanged',
  OnGroupApplicationAccepted = 'OnGroupApplicationAccepted',
  OnGroupApplicationRejected = 'OnGroupApplicationRejected',

  UploadComplete = 'UploadComplete',
  OnRecvCustomBusinessMessage = 'OnRecvCustomBusinessMessage',
  OnUserStatusChanged = 'OnUserStatusChanged',
  OnUserInputStatusChanged = 'OnUserInputStatusChanged',
  OnUserCommandAdd = 'OnUserCommandAdd',
  OnUserCommandDelete = 'OnUserCommandDelete',
  OnUserCommandUpdate = 'OnUserCommandUpdate',
  OnUploadLogsProgress = 'OnUploadLogsProgress',

  OnReceiveNewInvitation = 'OnReceiveNewInvitation',
  OnInviteeAccepted = 'OnInviteeAccepted',
  OnInviteeRejected = 'OnInviteeRejected',
  OnInvitationCancelled = 'OnInvitationCancelled',
  OnHangUp = 'OnHangUp',
  OnInvitationTimeout = 'OnInvitationTimeout',
  OnInviteeAcceptedByOtherDevice = 'OnInviteeAcceptedByOtherDevice',
  OnInviteeRejectedByOtherDevice = 'OnInviteeRejectedByOtherDevice',
  OnStreamChange = 'OnStreamChange',
  OnRoomParticipantConnected = 'OnRoomParticipantConnected',
  OnRoomParticipantDisconnected = 'OnRoomParticipantDisconnected',
  OnReceiveCustomSignal = 'OnReceiveCustomSignal',
  Open = 'Open',
  PartSize = 'PartSize',
  HashPartProgress = 'HashPartProgress',
  HashPartComplete = 'HashPartComplete',
  UploadID = 'UploadID',
  UploadPartComplete = 'UploadPartComplete',
  Complete = 'Complete',

  // unuse
  UnUsedEvent = 'UnUsedEvent',
}

/** @deprecated Use `SdkEvent` instead. */
export import CbEvents = SdkEvent;
